/**
 * controllers/billingController.js
 * ============================================================
 * Billing & Hospital Invoice Engine
 *
 * 1. Individual Trip Bills
 *    - Bills are auto-generated by tripController.completeTrip()
 *    - This controller handles: view, update payment, PDF generation endpoint
 *
 * 2. Monthly Hospital Invoice (Consolidated)
 *    - Aggregates all completed trips for a hospital in a given month
 *    - Applies tie-up discount from hospital contract
 *    - Calculates net payable
 *    - This is called by the cron job (scheduler.js) on month-end
 *    - Can also be triggered manually by Owner at any time
 *
 * ============================================================
 */

'use strict';

const { Bill, HospitalInvoice, Trip, Hospital, Income, Notification } = require('../models');
const fareCalculator = require('../utils/fareCalculator');

// ============================================================
// @route   GET /api/billing/bills
// @desc    List all trip bills with filters
// @access  Private [owner, telecaller]
// ============================================================
exports.getBills = async (req, res, next) => {
  try {
    const { paymentStatus, hospitalId, from, to, page = 1, limit = 30 } = req.query;
    const filter = {};

    if (paymentStatus) filter.paymentStatus = paymentStatus;
    if (hospitalId)    filter.hospital      = hospitalId;
    if (from || to) {
      filter.createdAt = {};
      if (from) filter.createdAt.$gte = new Date(from);
      if (to)   filter.createdAt.$lte = new Date(to);
    }

    const skip  = (Number(page) - 1) * Number(limit);
    const total = await Bill.countDocuments(filter);
    const bills = await Bill.find(filter)
      .populate('trip',     'tripNumber patientName patientPhone emergencyType completedAt')
      .populate('hospital', 'name city')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(Number(limit));

    // Totals for the filtered set
    const allFiltered = await Bill.find(filter).select('grandTotal paidAmount paymentStatus');
    const totals = {
      grossRevenue   : allFiltered.reduce((s, b) => s + (b.grandTotal || 0),   0),
      collected      : allFiltered.reduce((s, b) => s + (b.paidAmount  || 0),  0),
      pending        : allFiltered.filter(b => b.paymentStatus === 'pending').length,
      paidCount      : allFiltered.filter(b => b.paymentStatus === 'paid').length,
    };

    return res.json({ success: true, total, totals, bills });
  } catch (err) {
    next(err);
  }
};


// ============================================================
// @route   GET /api/billing/bills/:id
// @desc    Get single bill with full breakdown
// @access  Private [owner, telecaller]
// ============================================================
exports.getBillById = async (req, res, next) => {
  try {
    const bill = await Bill.findById(req.params.id)
      .populate({ path: 'trip', populate: [{ path: 'vehicle', select: 'registrationNumber' }, { path: 'driver', select: 'name' }] })
      .populate('hospital', 'name address phone email');

    if (!bill) return res.status(404).json({ success: false, message: 'Bill not found.' });
    return res.json({ success: true, bill });
  } catch (err) {
    next(err);
  }
};


// ============================================================
// @route   PUT /api/billing/bills/:id/payment
// @desc    Record payment against a bill
// @access  Private [owner, telecaller]
// ============================================================
exports.recordPayment = async (req, res, next) => {
  try {
    const { amount, paymentMode, notes } = req.body;
    const bill = await Bill.findById(req.params.id);
    if (!bill) return res.status(404).json({ success: false, message: 'Bill not found.' });

    bill.paidAmount    = (bill.paidAmount || 0) + Number(amount);
    bill.paymentMode   = paymentMode;
    bill.paymentStatus = bill.paidAmount >= bill.grandTotal ? 'paid' : 'partial';
    if (bill.paymentStatus === 'paid') bill.paidAt = new Date();
    if (notes) bill.notes = notes;
    await bill.save();

    return res.json({
      success: true,
      message: `Payment of ₹${amount} recorded. Status: ${bill.paymentStatus}.`,
      bill,
    });
  } catch (err) {
    next(err);
  }
};


// ============================================================
// @route   POST /api/billing/hospital-invoice/generate
// @desc    Generate (or regenerate) a monthly hospital invoice.
//
//          ALSO called by the cron job in scheduler.js at month-end.
//
//          Logic:
//          1. Find all completed trips for the hospital in the period
//             that are NOT yet included in any invoice.
//          2. Sum grandTotal of all matching bills.
//          3. Apply hospital tie-up discount.
//          4. Create / update HospitalInvoice document.
//          5. Auto-create Income entry for the net receivable.
//
// @access  Private [owner]
// ============================================================
exports.generateHospitalInvoice = async (req, res, next) => {
  try {
    const { hospitalId, month, year } = req.body;

    const m = Number(month);
    const y = Number(year);

    if (!hospitalId || !m || !y) {
      return res.status(400).json({ success: false, message: 'hospitalId, month, and year are required.' });
    }

    // ── 1. Fetch hospital and its contract terms ───────────────
    const hospital = await Hospital.findById(hospitalId);
    if (!hospital) return res.status(404).json({ success: false, message: 'Hospital not found.' });

    const discountPercent = hospital.tieUp?.discountPercent || 0;

    // ── 2. Date range ─────────────────────────────────────────
    const periodStart = new Date(y, m - 1, 1);
    const periodEnd   = new Date(y, m, 0, 23, 59, 59);

    // ── 3. Find all qualifying completed trips ─────────────────
    const trips = await Trip.find({
      dropHospital    : hospitalId,
      status          : 'completed',
      completedAt     : { $gte: periodStart, $lte: periodEnd },
      isHospitalBilled: false, // Not yet invoiced
    }).populate('billId');

    if (!trips.length) {
      return res.status(404).json({
        success: false,
        message: `No un-invoiced completed trips found for ${hospital.name} in ${m}/${y}.`,
        hospital: hospital.name,
        period  : `${m}/${y}`,
      });
    }

    // ── 4. Gather matching bills and compute totals ────────────
    const billIds    = trips.map(t => t.billId).filter(Boolean);
    const bills      = await Bill.find({ _id: { $in: billIds } });
    const grossAmount = bills.reduce((s, b) => s + (b.grandTotal || 0), 0);
    const discountAmt = Math.round(grossAmount * discountPercent / 100);
    const netPayable  = grossAmount - discountAmt;
    const dueDate     = new Date();
    dueDate.setDate(dueDate.getDate() + (hospital.tieUp?.creditDays || 30));

    const months = ['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

    // ── 5. Upsert invoice ─────────────────────────────────────
    const invoice = await HospitalInvoice.findOneAndUpdate(
      { hospital: hospitalId, 'billingPeriod.month': m, 'billingPeriod.year': y },
      {
        hospital        : hospitalId,
        billingPeriod   : { month: m, year: y },
        trips           : trips.map(t => t._id),
        bills           : billIds,
        totalTrips      : trips.length,
        grossAmount,
        discountPercent,
        discountAmount  : discountAmt,
        netPayable,
        dueDate,
        generatedBy     : req.user?._id,
        status          : 'draft',
      },
      { upsert: true, new: true }
    );

    // ── 6. Mark trips as hospital-billed ─────────────────────
    await Trip.updateMany(
      { _id: { $in: trips.map(t => t._id) } },
      { isHospitalBilled: true, 'billId': { $exists: true } }
    );

    // Link bills to this invoice
    await Bill.updateMany(
      { _id: { $in: billIds } },
      { invoiceId: invoice._id }
    );

    // ── 7. Auto-create Income entry for net receivable ─────────
    await Income.create({
      category   : 'hospital_credit',
      amount     : netPayable,
      description: `${hospital.name} — Invoice ${invoice._id} — ${months[m]} ${y}`,
      date       : new Date(),
      invoice    : invoice._id,
      recordedBy : req.user?._id,
    });

    // ── 8. Notify owner ───────────────────────────────────────
    await Notification.create({
      type      : 'salary_generated',
      title     : `🏥 Invoice Generated: ${hospital.name}`,
      message   : `${trips.length} trips · ₹${grossAmount.toLocaleString('en-IN')} gross · ₹${netPayable.toLocaleString('en-IN')} net payable`,
      severity  : 'info',
      targetRole: 'owner',
    });

    await invoice.populate('hospital', 'name address');

    return res.status(201).json({
      success: true,
      message: `Invoice generated for ${hospital.name} — ${months[m]} ${y}`,
      invoice,
      summary: { totalTrips: trips.length, grossAmount, discountPercent, discountAmount: discountAmt, netPayable },
    });
  } catch (err) {
    next(err);
  }
};


// ============================================================
// @route   GET /api/billing/hospital-invoices
// @desc    List all hospital invoices with filters
// @access  Private [owner]
// ============================================================
exports.getHospitalInvoices = async (req, res, next) => {
  try {
    const { hospitalId, status, year, page = 1, limit = 20 } = req.query;
    const filter = {};

    if (hospitalId) filter.hospital            = hospitalId;
    if (status)     filter.status              = status;
    if (year)       filter['billingPeriod.year'] = Number(year);

    const skip  = (Number(page) - 1) * Number(limit);
    const total = await HospitalInvoice.countDocuments(filter);
    const invoices = await HospitalInvoice.find(filter)
      .populate('hospital', 'name city')
      .sort({ 'billingPeriod.year': -1, 'billingPeriod.month': -1 })
      .skip(skip)
      .limit(Number(limit));

    return res.json({ success: true, total, invoices });
  } catch (err) {
    next(err);
  }
};


// ============================================================
// @route   PUT /api/billing/hospital-invoices/:id/status
// @desc    Update invoice status (sent, paid, overdue)
// @access  Private [owner]
// ============================================================
exports.updateInvoiceStatus = async (req, res, next) => {
  try {
    const { status } = req.body;
    const update = { status };
    if (status === 'sent') update.sentAt = new Date();
    if (status === 'paid') update.paidAt = new Date();

    const invoice = await HospitalInvoice.findByIdAndUpdate(req.params.id, update, { new: true });
    if (!invoice) return res.status(404).json({ success: false, message: 'Invoice not found.' });

    return res.json({ success: true, invoice });
  } catch (err) {
    next(err);
  }
};


// ============================================================
// @route   GET /api/billing/dashboard
// @desc    Owner financial dashboard aggregation
// @access  Private [owner]
// ============================================================
exports.getFinancialDashboard = async (req, res, next) => {
  try {
    const now        = new Date();
    const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
    const monthEnd   = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59);

    const [
      totalRevenue,
      pendingRevenue,
      completedTrips,
      avgFare,
      pendingInvoices,
    ] = await Promise.all([
      // Total collected this month
      Bill.aggregate([
        { $match: { createdAt: { $gte: monthStart, $lte: monthEnd }, paymentStatus: 'paid' } },
        { $group: { _id: null, total: { $sum: '$grandTotal' } } },
      ]),
      // Pending revenue
      Bill.aggregate([
        { $match: { createdAt: { $gte: monthStart, $lte: monthEnd }, paymentStatus: { $in: ['pending','partial'] } } },
        { $group: { _id: null, total: { $sum: { $subtract: ['$grandTotal', '$paidAmount'] } } } },
      ]),
      // Trip count this month
      Trip.countDocuments({ status: 'completed', completedAt: { $gte: monthStart, $lte: monthEnd } }),
      // Average fare
      Trip.aggregate([
        { $match: { status: 'completed', completedAt: { $gte: monthStart, $lte: monthEnd } } },
        { $group: { _id: null, avg: { $avg: '$grandTotal' } } },
      ]),
      // Pending hospital invoices
      HospitalInvoice.countDocuments({ status: { $in: ['sent', 'overdue'] } }),
    ]);

    return res.json({
      success: true,
      dashboard: {
        thisMonth: {
          collectedRevenue : totalRevenue[0]?.total   || 0,
          pendingRevenue   : pendingRevenue[0]?.total  || 0,
          completedTrips,
          avgFare          : Math.round(avgFare[0]?.avg || 0),
        },
        pendingInvoices,
      },
    });
  } catch (err) {
    next(err);
  }
};
